# Generated by Django 2.1.7 on 2019-05-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('image', models.CharField(max_length=100, verbose_name='Изображение')),
                ('release_date', models.DateField(verbose_name='Дата выхода')),
                ('lte_exists', models.CharField(max_length=100, verbose_name='Наличие LTE')),
                ('slug', models.CharField(max_length=100, verbose_name='Ссылка')),
            ],
        ),
    ]
