# Generated by Django 2.2.2 on 2019-06-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(verbose_name='порядковый номер')),
                ('name', models.CharField(max_length=15, verbose_name='название поля')),
                ('width', models.IntegerField(verbose_name='ширина поля')),
            ],
            options={
                'verbose_name': 'поле',
                'verbose_name_plural': 'поля',
            },
        ),
        migrations.CreateModel(
            name='TableFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FilePathField(path='/Users/britishpop/Documents/git/dj-homeworks/creating-project/application', verbose_name='путь к файлу')),
            ],
            options={
                'verbose_name': 'файл',
                'verbose_name_plural': 'файлы',
            },
        ),
    ]
