# Generated by Django 2.2.2 on 2019-06-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20190624_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.FileField(upload_to='articles/img/%Y/%m/%d/'),
        ),
    ]
