# Generated by Django 2.2.2 on 2019-06-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20190624_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.FileField(upload_to='media/%Y/%m/%d/'),
        ),
    ]
