# Generated by Django 2.2.2 on 2019-06-24 14:27

from django.db import migrations

def replace_media(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Article = apps.get_model('articles', 'Article')
    for article in Article.objects.all():
        article.img = article.img.url.replace('/media/articles/img', '')
        article.save()

class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20190624_1408'),
    ]

    operations = [
        migrations.RunPython(replace_media)
    ]
